# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import booking_pb2 as booking__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllBookings = channel.unary_stream(
                '/Bookings/GetAllBookings',
                request_serializer=booking__pb2.EmptyB.SerializeToString,
                response_deserializer=booking__pb2.Booking.FromString,
                _registered_method=True)
        self.GetTimesForBooking = channel.unary_stream(
                '/Bookings/GetTimesForBooking',
                request_serializer=booking__pb2.UserID.SerializeToString,
                response_deserializer=booking__pb2.TimeB.FromString,
                _registered_method=True)
        self.GetBookingForUser = channel.unary_unary(
                '/Bookings/GetBookingForUser',
                request_serializer=booking__pb2.UserID.SerializeToString,
                response_deserializer=booking__pb2.Booking.FromString,
                _registered_method=True)
        self.AddBookingByUser = channel.unary_unary(
                '/Bookings/AddBookingByUser',
                request_serializer=booking__pb2.Booking.SerializeToString,
                response_deserializer=booking__pb2.Response.FromString,
                _registered_method=True)


class BookingsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimesForBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookingForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBookingByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllBookings': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllBookings,
                    request_deserializer=booking__pb2.EmptyB.FromString,
                    response_serializer=booking__pb2.Booking.SerializeToString,
            ),
            'GetTimesForBooking': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTimesForBooking,
                    request_deserializer=booking__pb2.UserID.FromString,
                    response_serializer=booking__pb2.TimeB.SerializeToString,
            ),
            'GetBookingForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookingForUser,
                    request_deserializer=booking__pb2.UserID.FromString,
                    response_serializer=booking__pb2.Booking.SerializeToString,
            ),
            'AddBookingByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBookingByUser,
                    request_deserializer=booking__pb2.Booking.FromString,
                    response_serializer=booking__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Bookings', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Bookings', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bookings(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Bookings/GetAllBookings',
            booking__pb2.EmptyB.SerializeToString,
            booking__pb2.Booking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimesForBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Bookings/GetTimesForBooking',
            booking__pb2.UserID.SerializeToString,
            booking__pb2.TimeB.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookingForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Bookings/GetBookingForUser',
            booking__pb2.UserID.SerializeToString,
            booking__pb2.Booking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBookingByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Bookings/AddBookingByUser',
            booking__pb2.Booking.SerializeToString,
            booking__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
