# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x18\n\x06UserID\x12\x0e\n\x06userid\x18\x01 \x01(\t\"0\n\x07\x42ooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x15\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x06.TimeB\"%\n\x05TimeB\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t\"\x08\n\x06\x45mptyB2\xb3\x01\n\x08\x42ookings\x12\'\n\x0eGetAllBookings\x12\x07.EmptyB\x1a\x08.Booking\"\x00\x30\x01\x12)\n\x12GetTimesForBooking\x12\x07.UserID\x1a\x06.TimeB\"\x00\x30\x01\x12(\n\x11GetBookingForUser\x12\x07.UserID\x1a\x08.Booking\"\x00\x12)\n\x10\x41\x64\x64\x42ookingByUser\x12\x08.Booking\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERID']._serialized_start=17
  _globals['_USERID']._serialized_end=41
  _globals['_BOOKING']._serialized_start=43
  _globals['_BOOKING']._serialized_end=91
  _globals['_TIMEB']._serialized_start=93
  _globals['_TIMEB']._serialized_end=130
  _globals['_RESPONSE']._serialized_start=132
  _globals['_RESPONSE']._serialized_end=160
  _globals['_EMPTYB']._serialized_start=162
  _globals['_EMPTYB']._serialized_end=170
  _globals['_BOOKINGS']._serialized_start=173
  _globals['_BOOKINGS']._serialized_end=352
# @@protoc_insertion_point(module_scope)
